/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styled from "styled-components";

/**
 * MyComponent is the main component that renders the IconButton component.
 */
function MyComponent() {
    /**
     * Handles the click event on the IconButton.
     */
    const handleClick = () => {
        // Add click event logic here
    };

    return <IconButton onClick={handleClick} />;
}

/**
 * IconButton component represents a styled icon button.
 */
const IconButton = styled.button`
  align-self: end;
  width: 32px;
  height: 32px;
  background: none;
  border: none;
  cursor: pointer;

  svg {
    width: 100%;
    height: 100%;
  }
`;

export default MyComponent;