/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

/**
 * Main entryPageModel component
 */
function entryPageModel() {
  return (
    <>
      <div className="entryPageModel">
        <Header />
        <Main />
      </div>
      <style jsx>{`
        .entryPageModel {
          background-color: #fff;
          display: flex;
          flex-direction: column;
          padding: 39px 15px 80px 42px;
        }
        @media (max-width: 991px) {
          .entryPageModel {
            padding-left: 20px;
          }
        }
      `}</style>
    </>
  );
}

/**
 * Header component
 */
function Header() {
  return (
    <>
      <header className="header">
        <Logo />
      </header>
      <style jsx>{`
        .header {
          color: #000;
          font: 600 20px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .header {
            max-width: 100%;
          }
        }
      `}</style>
    </>
  );
}

/**
 * Logo component
 */
function Logo() {
  return (
    <>
      <div className="logo">Your Logo</div>
      <style jsx>{`
        .logo {
          color: #000;
          font: 600 20px Poppins, sans-serif;
        }
      `}</style>
    </>
  );
}

/**
 * Main component
 */
function Main() {
  return (
    <>
      <main className="main">
        <div className="content">
          <LoginForm />
          <ImageSection />
        </div>
      </main>
      <style jsx>{`
        .main {
          align-self: center;
          margin-top: 56px;
          width: 100%;
          max-width: 1314px;
        }
        @media (max-width: 991px) {
          .main {
            max-width: 100%;
            margin-top: 40px;
          }
        }
        .content {
          gap: 20px;
          display: flex;
        }
        @media (max-width: 991px) {
          .content {
            flex-direction: column;
            align-items: stretch;
            gap: 0px;
          }
        }
      `}</style>
    </>
  );
}

/**
 * LoginForm component
 */
function LoginForm() {
  return (
    <>
      <section className="login-form">
        <div className="form-container">
          <WelcomeText />
          <SignInText />
          <DescriptionText />
          <UsernameInput />
          <PasswordInput />
          <RememberMeCheckbox />
          <LoginButton />
          <RegisterText />
        </div>
      </section>
      <style jsx>{`
        .login-form {
          display: flex;
          flex-direction: column;
          line-height: normal;
          width: 38%;
          margin-left: 0px;
        }
        @media (max-width: 991px) {
          .login-form {
            width: 100%;
          }
        }
        .form-container {
          border-radius: 10px;
          box-shadow: 0px 4px 64px 0px rgba(0, 0, 0, 0.05);
          border-color: rgba(135, 135, 135, 1);
          border-style: solid;
          border-width: 1px;
          background-color: #fff;
          display: flex;
          flex-grow: 1;
          flex-direction: column;
          width: 100%;
          padding: 44px 35px;
        }
        @media (max-width: 991px) {
          .form-container {
            max-width: 100%;
            padding: 0 20px;
          }
        }
      `}</style>
    </>
  );
}

/**
 * WelcomeText component
 */
function WelcomeText() {
  return (
    <>
      <h1 className="welcome-text">Welcome !</h1>
      <style jsx>{`
        .welcome-text {
          color: #000;
          font: 300 25px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .welcome-text {
            max-width: 100%;
          }
        }
      `}</style>
    </>
  );
}

/**
 * SignInText component
 */
function SignInText() {
  return (
    <>
      <h2 className="sign-in-text">Sign in to</h2>
      <style jsx>{`
        .sign-in-text {
          color: #000;
          margin-top: 49px;
          font: 500 31px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .sign-in-text {
            max-width: 100%;
            margin-top: 40px;
          }
        }
      `}</style>
    </>
  );
}

/**
 * DescriptionText component
 */
function DescriptionText() {
  return (
    <>
      <p className="description-text">Lorem Ipsum is simply</p>
      <style jsx>{`
        .description-text {
          color: #000;
          margin-top: 12px;
          font: 400 16px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .description-text {
            max-width: 100%;
          }
        }
      `}</style>
    </>
  );
}

/**
 * UsernameInput component
 */
function UsernameInput() {
  return (
    <>
      <div className="username-input">
        <label htmlFor="username" className="input-label">
          User name
        </label>
        <div className="input-container">
          <input
            type="text"
            id="username"
            className="input-field"
            placeholder="Enter your user name"
          />
        </div>
      </div>
      <style jsx>{`
        .username-input {
          justify-content: center;
          display: flex;
          margin-top: 57px;
          flex-direction: column;
        }
        @media (max-width: 991px) {
          .username-input {
            max-width: 100%;
            margin-top: 40px;
          }
        }
        .input-label {
          color: #000;
          font: 400 16px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .input-label {
            max-width: 100%;
          }
        }
        .input-container {
          display: flex;
          margin-top: 15px;
          flex-direction: column;
          font-size: 14px;
          color: #ababab;
          font-weight: 300;
          justify-content: center;
        }
        @media (max-width: 991px) {
          .input-container {
            max-width: 100%;
          }
        }
        .input-field {
          font-family: Poppins, sans-serif;
          border-radius: 6px;
          border-color: rgba(40, 40, 40, 1);
          border-style: solid;
          border-width: 1px;
          background-color: #fff;
          align-items: start;
          justify-content: center;
          padding: 23px 27px;
        }
        @media (max-width: 991px) {
          .input-field {
            max-width: 100%;
            padding: 0 20px;
          }
        }
      `}</style>
    </>
  );
}

/**
 * PasswordInput component
 */
function PasswordInput() {
  return (
    <>
      <div className="password-input">
        <label htmlFor="password" className="input-label">
          Password
        </label>
        <div className="input-container">
          <div className="input-wrapper">
            <input
              type="password"
              id="password"
              className="input-field"
              placeholder="Enter your Password"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/97d6029f3f1f2da68a035f6526f6bd3a7542a98d10fe7bb1c013e7b91b0abcdc?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&"
              className="password-icon"
              alt="Password visibility toggle"
            />
          </div>
        </div>
      </div>
      <style jsx>{`
        .password-input {
          justify-content: center;
          display: flex;
          margin-top: 44px;
          flex-direction: column;
        }
        @media (max-width: 991px) {
          .password-input {
            max-width: 100%;
            margin-top: 40px;
          }
        }
        .input-label {
          color: #000;
          font: 400 16px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .input-label {
            max-width: 100%;
          }
        }
        .input-container {
          display: flex;
          margin-top: 15px;
          flex-direction: column;
          font-size: 14px;
          color: #ababab;
          font-weight: 300;
          justify-content: center;
        }
        @media (max-width: 991px) {
          .input-container {
            max-width: 100%;
          }
        }
        .input-wrapper {
          border-radius: 6px;
          border-color: rgba(40, 40, 40, 1);
          border-style: solid;
          border-width: 1px;
          background-color: #fff;
          display: flex;
          gap: 20px;
          padding: 19px 28px;
        }
        @media (max-width: 991px) {
          .input-wrapper {
            max-width: 100%;
            flex-wrap: wrap;
            padding: 0 20px;
          }
        }
        .input-field {
          font-family: Poppins, sans-serif;
          flex-grow: 1;
          flex-basis: auto;
        }
        .password-icon {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 21px;
        }
      `}</style>
    </>
  );
}

/**
 * RememberMeCheckbox component
 */
function RememberMeCheckbox() {
  return (
    <>
      <div className="remember-me">
        <div className="checkbox-wrapper">
          <input type="checkbox" id="remember-me" className="checkbox-input" />
          <label htmlFor="remember-me" className="checkbox-label">
            Remember me
          </label>
        </div>
        <a href="#" className="forgot-password">
          Forgot Password ?
        </a>
      </div>
      <style jsx>{`
        .remember-me {
          display: flex;
          margin-top: 26px;
          width: 100%;
          gap: 20px;
          font-size: 12px;
          font-weight: 300;
        }
        @media (max-width: 991px) {
          .remember-me {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .checkbox-wrapper {
          display: flex;
          gap: 10px;
          color: #000;
          flex: 1;
        }
        .checkbox-input {
          border-color: rgba(0, 0, 0, 1);
          border-style: solid;
          border-width: 1px;
          background-color: #fff;
          width: 15px;
          height: 15px;
        }
        .checkbox-label {
          font-family: Poppins, sans-serif;
        }
        .forgot-password {
          color: #4d4d4d;
          font-family: Poppins, sans-serif;
          flex-grow: 1;
          flex-basis: auto;
        }
      `}</style>
    </>
  );
}

/**
 * LoginButton component
 */
function LoginButton() {
  return (
    <>
      <button className="login-button">Login</button>
      <style jsx>{`
        .login-button {
          border-radius: 6px;
          background-color: #000;
          margin-top: 38px;
          align-items: center;
          color: #fff;
          white-space: nowrap;
          justify-content: center;
          padding: 21px 60px;
          font: 500 16px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .login-button {
            max-width: 100%;
            white-space: initial;
            padding: 0 20px;
          }
        }
      `}</style>
    </>
  );
}

/**
 * RegisterText component
 */
function RegisterText() {
  return (
    <>
      <p className="register-text">
        <span className="text-muted">Don't have an Account ?</span>{" "}
        <a href="#" className="register-link">
          Register
        </a>
      </p>
      <style jsx>{`
        .register-text {
          color: #000;
          align-self: center;
          margin-top: 61px;
          font: 300 16px Poppins, sans-serif;
        }
        @media (max-width: 991px) {
          .register-text {
            margin-top: 40px;
          }
        }
        .text-muted {
          color: rgba(125, 125, 125, 1);
        }
        .register-link {
          font-weight: 600;
        }
      `}</style>
    </>
  );
}

/**
 * ImageSection component
 */
function ImageSection() {
  return (
    <>
      <section className="image-section">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4327769a8656642e921d123dae9bfdad5646c6a99a7f7826e45af78b68797cc8?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&"
          className="section-image"
          alt="Decorative image"
        />
      </section>
      <style jsx>{`
        .image-section {
          display: flex;
          flex-direction: column;
          line-height: normal;
          width: 62%;
          margin-left: 20px;
        }
        @media (max-width: 991px) {
          .image-section {
            width: 100%;
          }
        }
        .section-image {
          aspect-ratio: 1.27;
          object-fit: auto;
          object-position: center;
          width: 100%;
          margin-top: 13px;
        }
        @media (max-width: 991px) {
          .section-image {
            max-width: 100%;
          }
        }
      `}</style>
    </>
  );
}

export default entryPageModel;