/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styled from "styled-components";

/**
 * MyComponent is the main component of the application
 * It renders the login form and the background image
 */
function MyComponent() {
  /**
   * Handles the click event on the login button
   */
  const handleLoginClick = () => {
    // TODO: Implement login logic
    console.log("Login button clicked");
  };

  /**
   * Handles the click event on the register button
   */
  const handleRegisterClick = () => {
    // TODO: Implement register logic
    console.log("Register button clicked");
  };

  /**
   * Handles the click event on the forgot password button
   */
  const handleForgotPasswordClick = () => {
    // TODO: Implement forgot password logic
    console.log("Forgot password button clicked");
  };

  return (
    <Div>
      <Div2>
        <Img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/be16d37bd26e364da58a5965b54a0fb7ba80354d770d1eaaf56071225560ecb7?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&" />
        <Div3>
          <Div4>Lorem Ipsum is simply </Div4>
          <Div5>Lorem Ipsum is simply </Div5>
        </Div3>
      </Div2>
      <Div6>
        <Div7>
          <Div8>Your Logo</Div8>
          <Div9>Welcome to lorem..!</Div9>
          <Div10>
            <LoginButton onClick={handleLoginClick}>Login</LoginButton>
            <RegisterButton onClick={handleRegisterClick}>
              Register
            </RegisterButton>
          </Div10>
        </Div7>
        <Div13>
          Lorem Ipsum is simply dummy text of the printing and typesetting
          industry.
        </Div13>
        <Div14>User name</Div14>
        <Div15>Enter your User name</Div15>
        <Div16>Password</Div16>
        <Div17>
          <Div18>Enter your Password</Div18>
          <Img2 loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4c0d86f6395c2f82e77807a30e0718c5b6107d2c283d1a6f0aac3e92e92d251?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&" />
        </Div17>
        <Div19>
          <Div20>
            <Div21 />
            <Div22>Rememebr me</Div22>
          </Div20>
          <ForgotPasswordButton onClick={handleForgotPasswordClick}>
            Forgot Password ?
          </ForgotPasswordButton>
        </Div19>
        <LoginButton onClick={handleLoginClick}>Login</LoginButton>
      </Div6>
    </Div>
  );
}

const Div = styled.div`
  background-color: #fffefc;
  display: flex;
  gap: 20px;
  justify-content: space-between;
  padding: 38px 47px;
  @media (max-width: 991px) {
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const Div2 = styled.div`
  disply: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
  display: flex;
  min-height: 825px;
  gap: 0px;
  color: #fff;
  justify-content: center;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Img = styled.img`
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
`;

const Div3 = styled.div`
  position: relative;
  border-radius: 29px;
  background: linear-gradient(
    180deg,
    rgba(151, 118, 68, 0.35) 0%,
    rgba(0, 0, 0, 0.35) 100%
  );
  display: flex;
  flex-direction: column;
  align-items: start;
  gap: 19px;
  padding: 69px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const Div4 = styled.div`
  margin-top: 602px;
  gap: 0px;
  font: 700 37px Poppins, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
    flex-wrap: wrap;
  }
`;

const Div5 = styled.div`
  margin-top: 19px;
  gap: 0px;
  font: 400 25px Poppins, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Div6 = styled.div`
  align-self: start;
  display: flex;
  margin-top: 18px;
  flex-direction: column;
  gap: 18px;
  font-size: 16px;
  font-weight: 400;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Div7 = styled.div`
  display: flex;
  width: 100%;
  padding-left: 53px;
  flex-direction: column;
  align-items: flex-start;
  gap: 20px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding-left: 20px;
  }
`;

const Div8 = styled.div`
  color: #000;
  align-self: end;
  gap: 0px;
  font: 600 20px Poppins, sans-serif;
`;

const Div9 = styled.div`
  color: #000;
  font-family: Poppins, sans-serif;
  align-self: center;
  gap: 0px;
  margin: 27px 0 0 27px;
`;

const Div10 = styled.div`
  border-radius: 33px;
  background-color: #f8eddd;
  align-self: start;
  display: flex;
  margin-top: 30px;
  gap: 20px;
  white-space: nowrap;
  padding: 10px 13px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    white-space: initial;
  }
`;

const LoginButton = styled.button`
  font-family: Poppins, sans-serif;
  border-radius: 33px;
  background-color: #9e896a;
  align-items: start;
  color: #fff;
  justify-content: center;
  padding: 12px 51px;
  border: none;
  cursor: pointer;
  @media (max-width: 991px) {
    white-space: initial;
    padding: 0 20px;
  }
`;

const RegisterButton = styled.button`
  color: #9e896a;
  font-family: Poppins, sans-serif;
  gap: 0px;
  flex-grow: 1;
  flex-basis: auto;
  margin: auto 0;
  background-color: transparent;
  border: none;
  cursor: pointer;
`;

const Div13 = styled.div`
  color: #5b5b5b;
  font-family: Poppins, sans-serif;
  margin-top: 58px;
  gap: 0px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    margin-top: 40px;
  }
`;

const Div14 = styled.div`
  color: #000;
  font-family: Poppins, sans-serif;
  margin-top: 52px;
  gap: 0px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    margin-top: 40px;
  }
`;

const Div15 = styled.div`
  border-radius: 40px;
  border-color: rgba(158, 137, 106, 1);
  border-style: solid;
  border-width: 1px;
  background-color: #fff;
  margin-top: 18px;
  align-items: start;
  color: #acacac;
  justify-content: center;
  padding: 20px 31px;
  font: 300 15px Poppins, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const Div16 = styled.div`
  color: #000;
  font-family: Poppins, sans-serif;
  margin-top: 36px;
  gap: 0px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Div17 = styled.div`
  border-radius: 40px;
  border-color: rgba(158, 137, 106, 1);
  border-style: solid;
  border-width: 1px;
  background-color: #fff;
  display: flex;
  margin-top: 18px;
  gap: 20px;
  font-size: 15px;
  color: #acacac;
  font-weight: 300;
  padding: 18px 80px 18px 36px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const Div18 = styled.div`
  font-family: Poppins, sans-serif;
  gap: 0px;
  flex-grow: 1;
  flex-basis: auto;
`;

const Img2 = styled.img`
  aspect-ratio: 1;
  object-fit: auto;
  object-position: center;
  width: 18px;
  gap: 0px;
`;

const Div19 = styled.div`
  display: flex;
  margin-top: 25px;
  width: 100%;
  gap: 20px;
  font-size: 12px;
  color: #000;
  font-weight: 300;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Div20 = styled.div`
  display: flex;
  gap: 10px;
`;

const Div21 = styled.div`
  border-color: rgba(0, 0, 0, 1);
  border-style: solid;
  border-width: 1px;
  background-color: #fff;
  width: 15px;
  height: 15px;
  gap: 0px;
`;

const Div22 = styled.div`
  font-family: Poppins, sans-serif;
  gap: 0px;
`;

const ForgotPasswordButton = styled.button`
  font-family: Poppins, sans-serif;
  gap: 0px;
  flex-grow: 1;
  flex-basis: auto;
  background-color: transparent;
  border: none;
  cursor: pointer;
`;

export default MyComponent;