/**
 * This code was generated by Builder.io.
 *  Landing page UI Kit
 */
import * as React from "react";
import styled from "styled-components";
import { Button } from "@aws-amplify/ui-react";

export default function GettingStarted() {
    return (
        <Div>
            <Div2>
                <Div3>
                    <Column>
                        <Img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/c7774c146efdab2920e36ffcfaff98504e480d042fda2619b2c3a7c8d5609a96?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&"
                        />
                    </Column>
                    <Column2>
                        <Div4>
                            <Div5>Get Landing Page UI Kit Today!</Div5>
                            <Div6>
                                Break the Figma limits and explore the endless possibilities
                                with Anima.
                            </Div6>
                            <Button1
                                variant="primary"
                                endIcon={
                                    <Img2
                                        loading="lazy"
                                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8344ce87c5e881a2d54710ce188182796f31f94d9f573709fef6b4b83e3f543c?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&"
                                    />
                                }
                            >
                                Get Started
                            </Button1>
                        </Div4>
                    </Column2>
                </Div3>
            </Div2>
        </Div>
    );
}

const Div = styled.div`
  justify-content: center;
  background-color: var(--Neutral---Zircon, #f8f9ff);
  display: flex;
  flex-direction: column;
  padding: 80px 55px;
  @media (max-width: 991px) {
    padding: 0 20px;
  }
`;

const Div2 = styled.div`
  margin-top: 40px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const Div3 = styled.div`
  gap: 20px;
  display: flex;
  @media (max-width: 991px) {
    flex-direction: column;
    align-items: stretch;
    gap: 0px;
  }
`;

const Column = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 50%;
  margin-left: 0px;
  @media (max-width: 991px) {
    width: 100%;
  }
`;

const Img = styled.img`
  aspect-ratio: 1.2;
  object-fit: auto;
  object-position: center;
  width: 100%;
  flex-grow: 1;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const Column2 = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 50%;
  margin-left: 20px;
  @media (max-width: 991px) {
    width: 100%;
  }
`;

const Div4 = styled.div`
  display: flex;
  flex-direction: column;
  align-self: stretch;
  margin: auto 0;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const Div5 = styled.div`
  color: var(--Onboarding-background-grey, #2d2d2d);
  letter-spacing: -1px;
  font: 700 50px/65px Poppins, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    font-size: 40px;
    line-height: 58px;
  }
`;

const Div6 = styled.div`
  color: var(--Onboarding-background-grey, #2d2d2d);
  margin-top: 20px;
  font: 400 21px/32px Mulish, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const Button1 = styled(Button)`
  justify-content: center;
  align-self: start;
  margin-top: 40px;
`;

const Img2 = styled.img`
  aspect-ratio: 1;
  object-fit: auto;
  object-position: center;
  width: 20px;
  align-self: stretch;
  margin: auto 0;
`;