/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styled from "styled-components";

interface ImageProps {
  src: string;
  alt: string;
}

const Image = ({ src, alt }: ImageProps) => {
  return <StyledImage src={src} alt={alt} loading="lazy" />;
};

const StyledImage = styled.img`
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
`;

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
  onClick?: () => void;
}

const Button = ({ children, className, onClick }: ButtonProps) => {
  return (
    <StyledButton className={className} onClick={onClick}>
      {children}
    </StyledButton>
  );
};

const StyledButton = styled.button`
  font-family: Poppins, sans-serif;
  border-radius: 33px;
  background-color: #9e896a;
  color: #fff;
  padding: 12px 51px;
  border: none;
  cursor: pointer;

  @media (max-width: 991px) {
    white-space: initial;
    padding: 0 20px;
  }
`;

const LoginPage = () => {
  const handleLogin = () => {
    console.log("Login button clicked");
  };

  const handleRegister = () => {
    console.log("Register button clicked");
  };

  const handleForgotPassword = () => {
    console.log("Forgot password clicked");
  };

  const handleRememberMe = () => {
    console.log("Remember me checkbox clicked");
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("Form submitted");
  };

  return (
    <PageWrapper>
      <HeroSection>
        <Image src="https://cdn.builder.io/api/v1/image/assets/TEMP/be16d37bd26e364da58a5965b54a0fb7ba80354d770d1eaaf56071225560ecb7?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&" alt="Hero Image" />
        <HeroContent>
          <HeroTitle>Lorem Ipsum is simply</HeroTitle>
          <HeroSubtitle>Lorem Ipsum is simply</HeroSubtitle>
        </HeroContent>
      </HeroSection>
      <LoginSection>
        <Header>
          <Logo>Your Logo</Logo>
          <Heading>Welcome to lorem..!</Heading>
          <ButtonGroup>
            <Button onClick={handleLogin}>Login</Button>
            <RegisterButton onClick={handleRegister}>Register</RegisterButton>
          </ButtonGroup>
        </Header>
        <LoginDescription>
          Lorem Ipsum is simply dummy text of the printing and typesetting
          industry.
        </LoginDescription>
        <form onSubmit={handleSubmit}>
          <Label htmlFor="username">User name</Label>
          <Input type="text" id="username" placeholder="Enter your User name" required />
          <Label htmlFor="password">Password</Label>
          <PasswordInputWrapper>
            <PasswordInput
              type="password"
              id="password"
              placeholder="Enter your Password"
              required
            />
            <EyeIcon src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4c0d86f6395c2f82e77807a30e0718c5b6107d2c283d1a6f0aac3e92e92d251?apiKey=58b1c0d7d39f443581e9f17d0f64bb4b&" alt="Toggle Password Visibility" />
          </PasswordInputWrapper>
          <RememberMeWrapper>
            <Checkbox type="checkbox" id="rememberMe" onChange={handleRememberMe} />
            <Label htmlFor="rememberMe">Remember me</Label>
            <ForgotPassword onClick={handleForgotPassword}>
              Forgot Password?
            </ForgotPassword>
          </RememberMeWrapper>
          <LoginButton type="submit">Login</LoginButton>
        </form>
      </LoginSection>
    </PageWrapper>
  );
};

const PageWrapper = styled.div`
  background-color: #fffefc;
  display: flex;
  gap: 20px;
  justify-content: space-between;
  padding: 38px 47px;

  @media (max-width: 991px) {
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const HeroSection = styled.section`
  position: relative;
  display: flex;
  min-height: 825px;
  color: #fff;
  justify-content: center;
  overflow: hidden;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const HeroContent = styled.div`
  position: relative;
  border-radius: 29px;
  background: linear-gradient(
    180deg,
    rgba(151, 118, 68, 0.35) 0%,
    rgba(0, 0, 0, 0.35) 100%
  );
  display: flex;
  flex-direction: column;
  align-items: start;
  gap: 19px;
  padding: 69px;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const HeroTitle = styled.h1`
  margin-top: 602px;
  font: 700 37px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
    flex-wrap: wrap;
  }
`;

const HeroSubtitle = styled.h2`
  margin-top: 19px;
  font: 400 25px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const LoginSection = styled.section`
  align-self: start;
  display: flex;
  margin-top: 18px;
  flex-direction: column;
  gap: 18px;
  font-size: 16px;
  font-weight: 400;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Header = styled.header`
  display: flex;
  width: 100%;
  padding-left: 53px;
  flex-direction: column;
  align-items: flex-start;
  gap: 20px;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding-left: 20px;
  }
`;

const Logo = styled.h1`
  color: #000;
  align-self: end;
  font: 600 20px Poppins, sans-serif;
`;

const Heading = styled.h2`
  color: #000;
  font-family: Poppins, sans-serif;
  align-self: center;
  margin: 27px 0 0 27px;
`;

const ButtonGroup = styled.div`
  border-radius: 33px;
  background-color: #f8eddd;
  align-self: start;
  display: flex;
  margin-top: 30px;
  gap: 20px;
  white-space: nowrap;
  padding: 10px 13px;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    white-space: initial;
  }
`;

const RegisterButton = styled(Button)`
  color: #9e896a;
  background-color: transparent;
  flex-grow: 1;
  flex-basis: auto;
  margin: auto 0;
`;

const LoginDescription = styled.p`
  color: #5b5b5b;
  font-family: Poppins, sans-serif;
  margin-top: 58px;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    margin-top: 40px;
  }
`;

const Label = styled.label`
  color: #000;
  font-family: Poppins, sans-serif;
  margin-top: 52px;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    margin-top: 40px;
  }
`;

const Input = styled.input`
  border-radius: 40px;
  border: 1px solid rgba(158, 137, 106, 1);
  background-color: #fff;
  margin-top: 18px;
  color: #acacac;
  padding: 20px 31px;
  font: 300 15px Poppins, sans-serif;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const PasswordInputWrapper = styled.div`
  border-radius: 40px;
  border: 1px solid rgba(158, 137, 106, 1);
  background-color: #fff;
  display: flex;
  margin-top: 18px;
  gap: 20px;
  font-size: 15px;
  color: #acacac;
  font-weight: 300;
  padding: 18px 80px 18px 36px;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    padding: 0 20px;
  }
`;

const PasswordInput = styled.input`
  font-family: Poppins, sans-serif;
  flex-grow: 1;
  flex-basis: auto;
  border: none;
  background-color: transparent;
`;

const EyeIcon = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 18px;
`;

const RememberMeWrapper = styled.div`
  display: flex;
  margin-top: 25px;
  width: 100%;
  gap: 20px;
  font-size: 12px;
  color: #000;
  font-weight: 300;
  align-items: center;

  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Checkbox = styled.input`
  border: 1px solid rgba(0, 0, 0, 1);
  background-color: #fff;
  width: 15px;
  height: 15px;
`;

const ForgotPassword = styled.button`
  font-family: Poppins, sans-serif;
  flex-grow: 1;
  flex-basis: auto;
  text-align: right;
  color: inherit;
  text-decoration: none;
  background: none;
  border: none;
  cursor: pointer;
`;

const LoginButton = styled(Button)`
  border-radius: 36px;
  align-self: end;
  width: 232px;
  max-width: 100%;
  margin: 62px 64px 0 0;
  padding: 17px 60px;

  @media (max-width: 991px) {
    white-space: initial;
    margin: 40px 10px 0 0;
    padding: 0 20px;
  }
`;

export default LoginPage;